site_name: farmOS.org
site_url: http://farmos.org
repo_url: https://github.com/farmOS
site_favicon: favicon.ico
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">farmOS.org</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
google_analytics: ['UA-56974603-1', 'farmos.org']
pages:
- Home: index.md
- User Guide:
    - Mapping your farm: guide/areas.md
    - Managing assets: guide/assets.md
    - Logging events: guide/logs.md
    - Movements and location: guide/location.md
    - Roles: guide/roles.md
- Hosting:
    - Installing: hosting/installing.md
    - Updating: hosting/updating.md
- Development:
    - Projects: development/projects.md
    - Issue Queues: development/issue-queues.md
    - Architecture: development/architecture.md
    - Best Practice: development/best-practice.md
- Contribute: contribute.md
theme: yeti

